
# source
services:
  interface:
    build: ./interface
    ports:
      - "${INTERFACE_PORT}:3000"
    volumes:
      - ./test/entree:/app/in
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SOCKET_URL=http://${DESTINATION_IP}:${SOCKET_PORT}
    depends_on:
      - runner

  runner:
    build: ./runner
    environment:
      - IP_PORT=${DESTINATION_IP}:${GRPC_PORT}
    volumes:
      - ./test/entree:/usr/src/app/in
    depends_on:
      - synced
      
# destination
  synced:
    build: ./synced
    ports:
      - "${SOCKET_PORT}:3521" # Socket.io
      - "${GRPC_PORT}:51500" # gRPC
    environment:
      - SOCKET_PORT=${SOCKET_PORT}
      - GRPC_PORT=${GRPC_PORT}
    volumes:
      - ./test/sortie:/usr/src/app/out